name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^7.2.0+1
  http: ^0.13.3
  flutter_spinkit: ^5.0.0

  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  json_annotation: ^4.7.0
  hydrated_bloc: ^9.0.0
  recase: ^4.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/loading.gif

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900